Fix cloudant library not being loaded
When nodejs app is deployed in Kubernetes and uses the
Cloudant DB it fails when trying to use credential URL
because the client library is not loaded in that code path.

Error shown by pod is similar to the followings:

```console
$ kubectl logs get-started-node-c689d597d-5btz9
> get-started-node@0.1.1 start /app
> node server.js

/app/server.js:177
  cloudant = Cloudant(process.env.CLOUDANT_URL);
             ^

TypeError: Cloudant is not a function

```

Fixes #23 which was closed by the OP.

Signed-off-by: Martin Hickey <martin.hickey@ie.ibm.com>